export const LoaderConfig = {
  back: require('../sprites/back_5699.png'),
  logo: require('../sprites/logo_3882.png'),
  decOne: require('../sprites/dec_1_5113.png'),
  oldStair: require('../sprites/old_stair_5437.png'),
  austin: require('../sprites/austin_4968.png'),
  layer: require('../sprites/layer_1_6040.png'),
  globe: require('../sprites/globe_5117.png'),
  plantOne: require('../sprites/plant_5112.png'),
  plantTwo: require('../sprites/plant_5118.png'),
  bookStand: require('../sprites/book_stand_5119.png'),
  table: require('../sprites/table_5610.png'),
  iconHummer: require('../sprites/icon_hammer_5429.png'),
  backForStair: require('../sprites/backForStair.png'),
  firstStairLogo: require('../sprites/01_5631.png'),
  secondStairLogo: require('../sprites/02_5630.png'),
  thirdStairLogo: require('../sprites/03_5629.png'),
  chosenBackForStair: require('../sprites/choosed_5415.png'),
  ok: require('../sprites/ok_5584.png'),
  newFirstStair: require('../sprites/new_stair_01_5614.png'),
  newSecondStair: require('../sprites/new_stair_02_5615.png'),
  newThirdStair: require('../sprites/new_stair_03_5616.png'),
  background: require('../sprites/layer_3_6045.png'),
  finalPicture: require('../sprites/layer_2_6044.png'),
  finalContinue: require('../sprites/btn_6049.png'),
};